import type { PatrolRecord } from "./types";

export function getDemoPatrolRecords(dateKey: string, societyId: string): PatrolRecord[] {
  const society = "Vihav Trade Center";

  return [
    {
      record_id: `${societyId}_${dateKey}_19_guard_amir`,
      society_id: societyId,
      society,
      date_key: dateKey,
      hour_start: `${dateKey}T19:00:00+05:30`,
      hour_window: "7:00 PM - 8:00 PM",
      guard_id: "guard_amir",
      guard_name: "Amir Khan",
      status: "IN_PROGRESS",
      completed_count: 7,
      total_points: 10,
      points_scanned: ["A1", "A2", "B1", "B2", "C1", "C2", "D1"],
      scans: [
        { point_id: "A1", point_name: "Main Gate", scanned_at: `${dateKey}T19:05:00+05:30` },
        { point_id: "A2", point_name: "Basement Entry", scanned_at: `${dateKey}T19:11:00+05:30` },
        { point_id: "B1", point_name: "Lift Lobby", scanned_at: `${dateKey}T19:19:00+05:30` },
        { point_id: "B2", point_name: "Parking Ramp", scanned_at: `${dateKey}T19:28:00+05:30` },
        { point_id: "C1", point_name: "Terrace Door", scanned_at: `${dateKey}T19:34:00+05:30` },
        { point_id: "C2", point_name: "Rear Exit", scanned_at: `${dateKey}T19:39:00+05:30` },
        { point_id: "D1", point_name: "Electrical Room", scanned_at: `${dateKey}T19:45:00+05:30` },
      ],
      updated_at: `${dateKey}T19:45:00+05:30`,
    },
    {
      record_id: `${societyId}_${dateKey}_18_guard_amir`,
      society_id: societyId,
      society,
      date_key: dateKey,
      hour_start: `${dateKey}T18:00:00+05:30`,
      hour_window: "6:00 PM - 7:00 PM",
      guard_id: "guard_amir",
      guard_name: "Amir Khan",
      status: "COMPLETED",
      completed_count: 10,
      total_points: 10,
      scans: [
        { point_id: "A1", point_name: "Main Gate", scanned_at: `${dateKey}T18:03:00+05:30` },
        { point_id: "D2", point_name: "Generator Room", scanned_at: `${dateKey}T18:51:00+05:30` },
      ],
      updated_at: `${dateKey}T18:54:00+05:30`,
    },
    {
      record_id: `${societyId}_${dateKey}_17_guard_rita`,
      society_id: societyId,
      society,
      date_key: dateKey,
      hour_start: `${dateKey}T17:00:00+05:30`,
      hour_window: "5:00 PM - 6:00 PM",
      guard_id: "guard_rita",
      guard_name: "Rita Sharma",
      status: "MISSED",
      completed_count: 4,
      total_points: 10,
      scans: { note: "Only four QR points were scanned before the hour closed." },
      updated_at: `${dateKey}T18:01:00+05:30`,
    },
    {
      record_id: `${societyId}_${dateKey}_16_guard_rita`,
      society_id: societyId,
      society,
      date_key: dateKey,
      hour_start: `${dateKey}T16:00:00+05:30`,
      hour_window: "4:00 PM - 5:00 PM",
      guard_id: "guard_rita",
      guard_name: "Rita Sharma",
      status: "COMPLETED",
      completed_count: 10,
      total_points: 10,
      scans: null,
      updated_at: `${dateKey}T16:58:00+05:30`,
    },
  ];
}
